# Data paths
data:
  base_dir: "data/raw/ml-1m"
  results_dir: "results"

# Preprocessing parameters
preprocessing:
  min_interactions: 5

# Evaluation parameters
evaluation:
  k: 10
  n_negative_samples: 100

# User model parameters
user_models:
  demographic:
    # No specific parameters
  
  behavioral:
    n_factors: 50
  
  hybrid:
    demo_config: {}
    behav_config:
      n_factors: 50

# Recommendation algorithms parameters
algorithms:
  knn:
    k: 10 